version: '3.8'

networks:
  k6:
  grafana:

services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=k6
    networks:
      - k6
      - grafana

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - ./grafana/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml:ro
      - ./grafana/k6-load-test-results_config.json:/var/lib/grafana/dashboards/k6-load-testing-results.json:ro
    depends_on:
      - influxdb
    networks:
      - grafana

  k6:
    image: grafana/k6:latest
    volumes:
      - ./k6:/scripts:ro
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    networks:
      - k6
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data:
